# Generated by Django 2.2.6 on 2019-10-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='duree',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='star',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
