# Generated by Django 2.2.5 on 2019-10-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_film_duree'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='acteurs',
            field=models.ManyToManyField(related_name='acteurs', to='movies.Star'),
        ),
    ]
